version: '3'
services:
  socket-queue:
    build: .
    image: &img socket-queue
    ports:
      - "8080:8080"
    command: -c /etc/socket-queue/config.json
    volumes:
      - ./sample-config.json:/etc/socket-queue/config.json
      - $PWD:/app

  echo-server:
    build: .
    image: *img
    ports:
      - "5000:5000"
    command: --vv --echoServerPort=5000
    volumes:
      - $PWD:/app

  test-client:
    build: .
    image: *img
    command: --testTargetHost=socket-queue --testTargetPort=8080 --testClients=10 --vv --testRealLife
    volumes:
      - $PWD:/app
