exports.byCode = {
  00: 'Approved',
  01: 'Refer to card issuer',
  02: 'Refer to card issuer\'s special condition',
  03: 'Invalid merchant or service provider',
  04: 'Pick up card',
  05: 'Do not honor',
  06: 'Error',
  07: 'Pick up card, special condition',
  08: 'Honour with identification',
  09: 'Request in progress',
  10: 'Approved for partial amount',
  11: 'Approved (VIP)',
  12: 'Invalid transaction',
  13: 'Invalid amount',
  14: 'No such card',
  15: 'No such issuer',
  16: 'Approved, update track 3',
  17: 'Customer cancellation',
  18: 'Customer dispute',
  19: 'Re-enter transaction',
  20: 'Invalid response',
  21: 'No action taken',
  22: 'Suspected malfunction',
  23: 'Unacceptable transaction fee',
  24: 'File update not supported by receiver',
  25: 'No such record',
  26: 'Duplicate record update, old record replaced',
  27: 'File update field edit error',
  28: 'File locked out while update',
  29: 'File update error, contact acquirer',
  30: 'Format error',
  31: 'Issuer signed-off',
  32: 'Completed partially',
  33: 'Expired card',
  34: 'Suspect Fraud',
  35: 'Pick-up, card acceptor contact acquirer',
  36: 'Pick up, card restricted',
  37: 'Pick up, call acquirer',
  38: 'Pick up, Allowable PIN tries exceed',
  39: 'No credit account (Visa ePay)',
  40: 'Requested function not supported',
  41: 'Pick up, lost card',
  42: 'No universal account',
  43: 'Pick up, stolen card',
  44: 'No investment account',
  45: 'Reserved for ISO use',
  46: 'Reserved for ISO use2',
  47: 'Reserved for ISO use3',
  48: 'Reserved for ISO use4',
  49: 'Reserved for ISO use5',
  50: 'Do not renew',
  51: 'Not sufficient funds',
  52: 'No checking account',
  53: 'No savings account',
  54: 'Expired Card',
  55: 'Incorrect PIN',
  56: 'No card record',
  57: 'Not permitted to client',
  58: 'Not permitted to POS',
  59: 'Suspected fraud',
  60: 'Card acceptor contact acquirer',
  61: 'Exceeds amount limit',
  62: 'Restricted card',
  63: 'Security violation',
  64: 'Wrong original amount',
  65: 'Exceeds frequency limit',
  66: 'Acceptor call acquirer',
  67: 'Card to be picked up at ATM',
  68: 'Response received too late',
  69: 'Reserved',
  70: 'Invalid transaction; contact card issuer',
  71: 'Decline PIN not changed',
  72: 'Reserved2',
  73: 'Reserved3',
  74: 'Reserved4',
  75: 'PIN tries exceeded',
  76: 'Wrong PIN, tries exceeded',
  77: 'Wrong Reference No.',
  78: 'Record Not Found',
  79: 'Already reversed',
  80: 'Network error',
  81: 'Foreign network error',
  82: 'Time-out at issuer',
  83: 'Transaction failed',
  84: 'Pre-authorization timed out',
  85: 'No reason to decline',
  86: 'Unable to verify PIN',
  87: 'Purchase Approval Only',
  88: 'Cryptographic failure',
  89: 'Authentication failure',
  90: 'Cutoff is in progress',
  91: 'Issuer unavailable',
  92: 'Router unavailable',
  93: 'Transaction cannot be completed',
  94: 'Duplicate Transmission',
  95: 'Reconcile error / Auth Not found',
  96: 'System malfunction'
};