exports.byCode = {
    000: 'Successful Transaction',
    001: 'Approve with ID. If transaction was Success, but MCC these is in next list  6010, 4829, 6051, 7995, 7511 – then reason code changes on 001',
    002: 'ATM performed a partial dispense',
    003: 'Successful Transaction',
    005: 'System Error',
    020: 'Successful transaction; used to indicate a negative balance in Field 4 on a Balance Inquiry',
    095: 'Reconcile Error',
    100: 'Do Not Honor Transaction',
    101: 'Expired Card',
    103: 'Call Issuer',
    104: 'Card is Restricted',
    105: 'Call Security',
    106: 'Excessive Pin Failures',
    107: 'Call Issuer',
    109: 'Invalid Merchant ID',
    110: 'Cannot Process Amount',
    111: 'Invalid Account - Retry',
    116: 'Insufficient Funds - Retry',
    117: 'Incorrect Pin',
    118: 'Forced Post, no Account on File',
    119: 'Transaction Not Permitted by Law',
    120: 'Not Permitted',
    121: 'Withdrawal Limit Exceeded - Retry',
    123: 'Limit Reached for Total Number of Transactions in Cycle',
    125: 'Bad Card',
    126: 'Pin Processing Error',
    127: 'Pin Processing Error',
    128: 'Pin Processing Error',
    200: 'Invalid Сard',
    201: 'Card Expired',
    202: 'Invalid Card',
    203: 'Call Security',
    204: 'Account Restricted',
    205: 'Call Security',
    206: 'Invalid Pin',
    208: 'Lost Card',
    209: 'Stolen Card',
    902: 'Invalid Transaction - Retry',
    903: 'Transaction Needs to Be Entered Again',
    904: 'The Message Received Was not Within Standards',
    905: 'Issuing Institution is Unknown',
    907: 'Issuer inoperative',
    908: 'Issuing Institution is Unknown',
    909: 'System Malfunction',
    910: 'Issuer Inoperative',
    911: 'SmartVista FE Has Knowledge of Any Attempt to Either Authorize or Deny the Transaction',
    912: 'Timeout Waiting for Response',
    913: 'Duplicate Transaction Received',
    914: 'Could not Find the Original Transaction',
    915: 'Amount Being Reversed is Greater than Original, or no Amount Being Reversed',
    920: 'Pin Processing Error',
    923: 'Request in Progress'
};